
SESSION_ID_LENGTH   = 32
MAX_PAYLOAD_LENGTH  = 0x10000

CLIENT_MAX_TRIES           = 5
CLIENT_RETRY_DELAY         = 5
CLIENT_MAX_FAILURE         = 5

CLIENT_INITIAL_POLL_INTERVAL       = 0.1        
CLIENT_POLL_INTERVAL_MULTIPLIER    = 1.5
CLIENT_MAX_POLL_INTERVAL           = 5

SERVER_TURNAROUND_TIMEOUT          = 0.05
SERVER_TURNAROUND_MAX              = 0.2

HEADER_SESSION_ID   = "X-Session-Id"
HEADER_MSGTYPE      = "X-MsgType"
HEADER_UDP_PKTS     = "X-UDP-Pkts"
HEADER_ERROR        = "X-Error"
HEADER_MODE         = "X-Mode"

MSGTYPE_DATA        = "DATA"
MSGTYPE_TERMINATE   = "TERM"

MODE_STREAM         = "STREAM"
